# Sample compose file
services:
  wiremock:
    image: "wiremock/wiremock:3.13.2"
    container_name: wiremock
    ports:
      - 8080:8080
    volumes:
#      - ./extensions:/var/wiremock/extensions
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]